# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRQhvA9d5wOeUHDrUIgND2aK3P8cp7Es
"""

!pip install -U crewai gradio openai

import os

from crewai import LLM

llm = LLM(
    model="gpt-4o-mini",
    temperature=0.3
)

try:
    response = llm.call("Reply only with the word OK.")
    print("✅ Model is working. Response:", response)
except Exception as e:
    print("❌ Model is NOT working.")
    print("Error:", e)

from crewai import Agent

terrain_agent = Agent(
    role="Terrain Analyst",
    goal="Analyze terrain risks for military missions",
    backstory="Experienced military terrain expert",
    llm=llm,
    verbose=True
)

weather_agent = Agent(
    role="Weather Analyst",
    goal="Analyze weather impact on mission",
    backstory="Defense meteorologist",
    llm=llm,
    verbose=True
)

threat_agent = Agent(
    role="Threat Analyst",
    goal="Assess threats and enemy presence",
    backstory="Tactical intelligence officer",
    llm=llm,
    verbose=True
)

resource_agent = Agent(
    role="Resource Planner",
    goal="Evaluate manpower and logistics",
    backstory="Military logistics planner",
    llm=llm,
    verbose=True
)

from crewai import Task, Crew
import gradio as gr

def run_mission(mission_details):

    terrain_task = Task(
        description=f"Analyze terrain risks for this mission: {mission_details}",
        agent=terrain_agent,
        expected_output="Terrain risk analysis"
    )

    weather_task = Task(
        description=f"Analyze weather impact for this mission: {mission_details}",
        agent=weather_agent,
        expected_output="Weather impact analysis"
    )

    threat_task = Task(
        description=f"Assess threats and enemy risks: {mission_details}",
        agent=threat_agent,
        expected_output="Threat assessment"
    )

    resource_task = Task(
        description=f"Evaluate resources and manpower: {mission_details}",
        agent=resource_agent,
        expected_output="Resource evaluation"
    )

    crew = Crew(
        agents=[terrain_agent, weather_agent, threat_agent, resource_agent],
        tasks=[terrain_task, weather_task, threat_task, resource_task],
        verbose=True
    )

    result = crew.kickoff()
    return str(result)

ui = gr.Interface(
    fn=run_mission,
    inputs=gr.Textbox(
        lines=5,
        label="Mission Details",
        placeholder="Area, weather, time, resources, objective..."
    ),
    outputs=gr.Textbox(
        lines=30,
        label="CrewAI Mission Output"
    ),
    title="AI-Powered Mission Planning Assistant",
    description="Multi-agent decision support system for defense missions"
)

ui.launch(server_name="0.0.0.0", server_port=7862)